/**
 * User model representing a registered user.
 */
export interface User {
  id: number;
  username: string;
  email: string;
}

/**
 * DTO for user registration.
 */
export interface RegisterDto {
  username: string;
  email: string;
  password: string;
}

/**
 * DTO for user login.
 */
export interface LoginDto {
  usernameOrEmail: string;
  password: string;
}

/**
 * Authentication response containing token and user info.
 */
export interface AuthResponse {
  token: string;
  expiresAt: Date;
  user: User;
}

/**
 * Project model for grouping time entries.
 */
export interface Project {
  id: number;
  name: string;
  colorCode?: string;
  hourlyRate?: number;
  autoCreateIncome: boolean;
  description?: string;
  isActive: boolean;
  createdAt: Date;
  totalHours: number;
}

/**
 * DTO for creating a project.
 */
export interface CreateProjectDto {
  name: string;
  colorCode?: string;
  hourlyRate?: number;
  autoCreateIncome?: boolean;
  description?: string;
}

/**
 * DTO for updating a project.
 */
export interface UpdateProjectDto {
  name?: string;
  colorCode?: string;
  hourlyRate?: number;
  autoCreateIncome?: boolean;
  description?: string;
  isActive?: boolean;
}

/**
 * Tag model for categorizing time entries.
 */
export interface Tag {
  id: number;
  name: string;
  colorCode?: string;
  createdAt: Date;
}

/**
 * DTO for creating a tag.
 */
export interface CreateTagDto {
  name: string;
  colorCode?: string;
}

/**
 * DTO for updating a tag.
 */
export interface UpdateTagDto {
  name?: string;
  colorCode?: string;
}

/**
 * Time entry model for tracking work sessions.
 */
export interface TimeEntry {
  id: number;
  startTime: Date;
  endTime?: Date;
  durationMinutes?: number;
  description?: string;
  nextSteps?: string;
  isRunning: boolean;
  project?: Project;
  tags: Tag[];
  createdAt: Date;
}

/**
 * DTO for starting a timer.
 */
export interface StartTimerDto {
  projectId?: number;
}

/**
 * DTO for stopping a timer.
 */
export interface StopTimerDto {
  projectId?: number;
  description?: string;
  nextSteps?: string;
  tagIds: number[];
}

/**
 * DTO for creating a manual time entry.
 */
export interface CreateTimeEntryDto {
  startTime: Date;
  endTime: Date;
  projectId?: number;
  description?: string;
  nextSteps?: string;
  tagIds: number[];
}

/**
 * DTO for updating a time entry.
 */
export interface UpdateTimeEntryDto {
  startTime?: Date;
  endTime?: Date;
  projectId?: number;
  description?: string;
  nextSteps?: string;
  tagIds?: number[];
}

/**
 * Filter DTO for time entries.
 */
export interface TimeEntryFilterDto {
  projectId?: number;
  startDate?: Date;
  endDate?: Date;
  tagIds?: number[];
  page?: number;
  pageSize?: number;
}

/**
 * Employer report model.
 */
export interface EmployerReport {
  project: Project;
  periodStart: Date;
  periodEnd: Date;
  totalHours: number;
  totalEarnings?: number;
  timeEntries: TimeEntry[];
}

/**
 * Transaction type enum.
 */
export enum TransactionType {
  Income = 0,
  Expense = 1
}

/**
 * Currency enum.
 */
export enum Currency {
  USD = 0,
  EUR = 1,
  RSD = 2
}

/**
 * Transaction category model.
 */
export interface TransactionCategory {
  id: number;
  name: string;
  type: TransactionType;
  icon?: string;
  colorCode?: string;
  isSystem: boolean;
}

/**
 * DTO for creating a transaction category.
 */
export interface CreateTransactionCategoryDto {
  name: string;
  type: TransactionType;
  icon?: string;
  colorCode?: string;
}

/**
 * DTO for updating a transaction category.
 */
export interface UpdateTransactionCategoryDto {
  name?: string;
  icon?: string;
  colorCode?: string;
}

/**
 * Transaction model.
 */
export interface Transaction {
  id: number;
  amount: number;
  currency: Currency;
  date: Date;
  category: TransactionCategory;
  description?: string;
  isAutoGenerated: boolean;
  linkedTimeEntryId?: number;
  createdAt: Date;
}

/**
 * DTO for creating a transaction.
 */
export interface CreateTransactionDto {
  amount: number;
  currency?: Currency;
  date: Date;
  categoryId: number;
  description?: string;
}

/**
 * DTO for updating a transaction.
 */
export interface UpdateTransactionDto {
  amount?: number;
  currency?: Currency;
  date?: Date;
  categoryId?: number;
  description?: string;
}

/**
 * Filter DTO for transactions.
 */
export interface TransactionFilterDto {
  type?: TransactionType;
  categoryId?: number;
  startDate?: Date;
  endDate?: Date;
  page?: number;
  pageSize?: number;
}

/**
 * Financial summary model.
 */
export interface FinancialSummary {
  totalIncome: number;
  totalExpenses: number;
  netBalance: number;
  periodStart: Date;
  periodEnd: Date;
}

/**
 * Dashboard statistics model.
 */
export interface DashboardStats {
  timeDistribution: TimeDistribution[];
  monthlyFlow: MonthlyFlow[];
  productivityHeatmap: DailyProductivity[];
  weeklyHours: number;
  monthlyHours: number;
  monthlyIncome: number;
  monthlyExpenses: number;
  activeProjectsCount: number;
  runningTimer?: TimeEntry;
}

/**
 * Time distribution data for pie chart.
 */
export interface TimeDistribution {
  projectId: number;
  projectName: string;
  colorCode?: string;
  totalHours: number;
  percentage: number;
}

/**
 * Monthly financial flow data for bar chart.
 */
export interface MonthlyFlow {
  month: number;
  year: number;
  label: string;
  income: number;
  expenses: number;
}

/**
 * Daily productivity data for heatmap.
 */
export interface DailyProductivity {
  date: Date;
  hours: number;
  intensityLevel: number;
}

/**
 * Paginated response wrapper.
 */
export interface PaginatedResponse<T> {
  items: T[];
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

/**
 * API response wrapper.
 */
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  message?: string;
  errors?: string[];
}
