using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LifeSyncTracker.API.Models.Entities;

/// <summary>
/// Supported currencies.
/// </summary>
public enum Currency
{
    USD = 0,
    EUR = 1,
    RSD = 2
}

/// <summary>
/// Represents a financial transaction (income or expense).
/// </summary>
public class Transaction
{
    /// <summary>
    /// Unique identifier for the transaction.
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Amount of the transaction.
    /// </summary>
    [Required]
    [Column(TypeName = "decimal(18,2)")]
    public decimal Amount { get; set; }

    /// <summary>
    /// Currency of the transaction.
    /// </summary>
    public Currency Currency { get; set; } = Currency.USD;

    /// <summary>
    /// Date of the transaction.
    /// </summary>
    [Required]
    public DateTime Date { get; set; }

    /// <summary>
    /// Optional description for the transaction.
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; set; }

    /// <summary>
    /// Whether this transaction was automatically created from a time entry.
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// Date and time when the transaction was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Date and time when the transaction was last updated.
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Foreign key to the category.
    /// </summary>
    [Required]
    public int CategoryId { get; set; }

    /// <summary>
    /// Foreign key to the user.
    /// </summary>
    [Required]
    public int UserId { get; set; }

    /// <summary>
    /// Foreign key to the linked time entry (if auto-generated).
    /// </summary>
    public int? LinkedTimeEntryId { get; set; }

    // Navigation properties

    /// <summary>
    /// The category of this transaction.
    /// </summary>
    [ForeignKey("CategoryId")]
    public virtual TransactionCategory Category { get; set; } = null!;

    /// <summary>
    /// The user who created this transaction.
    /// </summary>
    [ForeignKey("UserId")]
    public virtual User User { get; set; } = null!;

    /// <summary>
    /// The time entry this transaction was generated from (if any).
    /// </summary>
    [ForeignKey("LinkedTimeEntryId")]
    public virtual TimeEntry? LinkedTimeEntry { get; set; }
}
