using System.ComponentModel.DataAnnotations;
using LifeSyncTracker.API.Models.Entities;

namespace LifeSyncTracker.API.Models.DTOs;

/// <summary>
/// DTO for creating a new transaction category.
/// </summary>
public class CreateTransactionCategoryDto
{
    /// <summary>
    /// Name of the category.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Type of transactions this category is for.
    /// </summary>
    [Required]
    public TransactionType Type { get; set; }

    /// <summary>
    /// Optional icon name.
    /// </summary>
    [MaxLength(50)]
    public string? Icon { get; set; }

    /// <summary>
    /// Color code for visual identification.
    /// </summary>
    [MaxLength(20)]
    public string? ColorCode { get; set; }
}

/// <summary>
/// DTO for updating a transaction category.
/// </summary>
public class UpdateTransactionCategoryDto
{
    /// <summary>
    /// Name of the category.
    /// </summary>
    [MaxLength(100)]
    public string? Name { get; set; }

    /// <summary>
    /// Optional icon name.
    /// </summary>
    [MaxLength(50)]
    public string? Icon { get; set; }

    /// <summary>
    /// Color code for visual identification.
    /// </summary>
    [MaxLength(20)]
    public string? ColorCode { get; set; }
}

/// <summary>
/// DTO for transaction category response.
/// </summary>
public class TransactionCategoryDto
{
    /// <summary>
    /// Category ID.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Name of the category.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Type of transactions.
    /// </summary>
    public TransactionType Type { get; set; }

    /// <summary>
    /// Optional icon name.
    /// </summary>
    public string? Icon { get; set; }

    /// <summary>
    /// Color code.
    /// </summary>
    public string? ColorCode { get; set; }

    /// <summary>
    /// Whether this is a system category.
    /// </summary>
    public bool IsSystem { get; set; }
}

/// <summary>
/// DTO for creating a new transaction.
/// </summary>
public class CreateTransactionDto
{
    /// <summary>
    /// Amount of the transaction.
    /// </summary>
    [Required]
    [Range(0.01, double.MaxValue)]
    public decimal Amount { get; set; }

    /// <summary>
    /// Currency of the transaction.
    /// </summary>
    public Currency Currency { get; set; } = Currency.USD;

    /// <summary>
    /// Date of the transaction.
    /// </summary>
    [Required]
    public DateTime Date { get; set; }

    /// <summary>
    /// Category ID.
    /// </summary>
    [Required]
    public int CategoryId { get; set; }

    /// <summary>
    /// Optional description.
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; set; }
}

/// <summary>
/// DTO for updating a transaction.
/// </summary>
public class UpdateTransactionDto
{
    /// <summary>
    /// Amount of the transaction.
    /// </summary>
    [Range(0.01, double.MaxValue)]
    public decimal? Amount { get; set; }

    /// <summary>
    /// Currency of the transaction.
    /// </summary>
    public Currency? Currency { get; set; }

    /// <summary>
    /// Date of the transaction.
    /// </summary>
    public DateTime? Date { get; set; }

    /// <summary>
    /// Category ID.
    /// </summary>
    public int? CategoryId { get; set; }

    /// <summary>
    /// Optional description.
    /// </summary>
    [MaxLength(500)]
    public string? Description { get; set; }
}

/// <summary>
/// DTO for transaction response.
/// </summary>
public class TransactionDto
{
    /// <summary>
    /// Transaction ID.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Amount of the transaction.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Currency of the transaction.
    /// </summary>
    public Currency Currency { get; set; }

    /// <summary>
    /// Date of the transaction.
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Category information.
    /// </summary>
    public TransactionCategoryDto Category { get; set; } = null!;

    /// <summary>
    /// Optional description.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Whether this transaction was auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Linked time entry ID (if auto-generated).
    /// </summary>
    public int? LinkedTimeEntryId { get; set; }

    /// <summary>
    /// Creation date.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// DTO for transaction filtering.
/// </summary>
public class TransactionFilterDto
{
    /// <summary>
    /// Filter by transaction type.
    /// </summary>
    public TransactionType? Type { get; set; }

    /// <summary>
    /// Filter by category ID.
    /// </summary>
    public int? CategoryId { get; set; }

    /// <summary>
    /// Filter by start date (inclusive).
    /// </summary>
    public DateTime? StartDate { get; set; }

    /// <summary>
    /// Filter by end date (inclusive).
    /// </summary>
    public DateTime? EndDate { get; set; }

    /// <summary>
    /// Page number (1-based).
    /// </summary>
    public int Page { get; set; } = 1;

    /// <summary>
    /// Page size.
    /// </summary>
    public int PageSize { get; set; } = 20;
}

/// <summary>
/// DTO for financial summary.
/// </summary>
public class FinancialSummaryDto
{
    /// <summary>
    /// Total income.
    /// </summary>
    public decimal TotalIncome { get; set; }

    /// <summary>
    /// Total expenses.
    /// </summary>
    public decimal TotalExpenses { get; set; }

    /// <summary>
    /// Net balance (income - expenses).
    /// </summary>
    public decimal NetBalance { get; set; }

    /// <summary>
    /// Period start date.
    /// </summary>
    public DateTime PeriodStart { get; set; }

    /// <summary>
    /// Period end date.
    /// </summary>
    public DateTime PeriodEnd { get; set; }
}
