// <auto-generated />
using System;
using LifeSyncTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeSyncTracker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102222425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoCreateIncome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextSteps")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StartTime");

                    b.HasIndex("UserId", "IsRunning");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedTimeEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("LinkedTimeEntryId")
                        .IsUnique();

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#22C55E",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4168),
                            Icon = "pi-dollar",
                            IsSystem = true,
                            Name = "Salary",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#3B82F6",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4175),
                            Icon = "pi-briefcase",
                            IsSystem = true,
                            Name = "Freelance",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#8B5CF6",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4177),
                            Icon = "pi-chart-line",
                            IsSystem = true,
                            Name = "Investment",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#10B981",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4179),
                            Icon = "pi-plus",
                            IsSystem = true,
                            Name = "Other Income",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#F59E0B",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4181),
                            Icon = "pi-shopping-cart",
                            IsSystem = true,
                            Name = "Groceries",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#EF4444",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4183),
                            Icon = "pi-home",
                            IsSystem = true,
                            Name = "Rent",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "#F97316",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4184),
                            Icon = "pi-bolt",
                            IsSystem = true,
                            Name = "Utilities",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            ColorCode = "#6366F1",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4186),
                            Icon = "pi-car",
                            IsSystem = true,
                            Name = "Transportation",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            ColorCode = "#EC4899",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4187),
                            Icon = "pi-desktop",
                            IsSystem = true,
                            Name = "Software Subscription",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            ColorCode = "#14B8A6",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4189),
                            Icon = "pi-ticket",
                            IsSystem = true,
                            Name = "Entertainment",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            ColorCode = "#F43F5E",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4190),
                            Icon = "pi-heart",
                            IsSystem = true,
                            Name = "Healthcare",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            ColorCode = "#64748B",
                            CreatedAt = new DateTime(2026, 1, 2, 22, 24, 24, 747, DateTimeKind.Utc).AddTicks(4191),
                            Icon = "pi-minus",
                            IsSystem = true,
                            Name = "Other Expense",
                            Type = 1
                        });
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TimeEntryTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TagId", "TimeEntryId");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("TimeEntryTag");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.Project", b =>
                {
                    b.HasOne("LifeSyncTracker.API.Models.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.Tag", b =>
                {
                    b.HasOne("LifeSyncTracker.API.Models.Entities.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.TimeEntry", b =>
                {
                    b.HasOne("LifeSyncTracker.API.Models.Entities.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeSyncTracker.API.Models.Entities.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.Transaction", b =>
                {
                    b.HasOne("LifeSyncTracker.API.Models.Entities.TransactionCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LifeSyncTracker.API.Models.Entities.TimeEntry", "LinkedTimeEntry")
                        .WithOne("LinkedTransaction")
                        .HasForeignKey("LifeSyncTracker.API.Models.Entities.Transaction", "LinkedTimeEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LifeSyncTracker.API.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("LinkedTimeEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.TransactionCategory", b =>
                {
                    b.HasOne("LifeSyncTracker.API.Models.Entities.User", "User")
                        .WithMany("TransactionCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeEntryTag", b =>
                {
                    b.HasOne("LifeSyncTracker.API.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifeSyncTracker.API.Models.Entities.TimeEntry", null)
                        .WithMany()
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.Project", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.TimeEntry", b =>
                {
                    b.Navigation("LinkedTransaction");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.TransactionCategory", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LifeSyncTracker.API.Models.Entities.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Tags");

                    b.Navigation("TimeEntries");

                    b.Navigation("TransactionCategories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
